### PR TITLE
Create pull_request_template.md

### PR DESCRIPTION
**Pull request by derekcoughlan**
**I have included a suggested pull request template, please let me know your thoughts. The link below from Erika includes suggestions for what to include in your pull requests and includes examples:**

https://www.pullrequest.com/blog/writing-a-great-pull-request-description/

### CODE REVIEW

**Review by apiraam96 — APPROVED** [review]
Template looks good

**Comment by jesse-chou** [comment]
Template looks good

**Review by jesse-chou — APPROVED** [review]

**Review by jesse-chou — COMMENTED** [review]
looks good to me

**Review by danealexandersmith — APPROVED** [review]
Looks great.

**Review by apiraam96 — APPROVED** [review]
review

**Review by danealexandersmith — APPROVED** [review]

**Review by danealexandersmith — COMMENTED** [review]
Approved.

**Review by apiraam96 — COMMENTED** [review]
review test

**Review by jesse-chou — APPROVED** [review]

**Review by apiraam96 — APPROVED** [review]

**Review by jesse-chou — APPROVED** [review]

**Review by danealexandersmith — APPROVED** [review]

**Review by apiraam96 — APPROVED** [review]

**Pull request merged**
